### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by coutar-t** [kostiakoval/SpeedLog#10]
Now that Swift 3 is available, it could be useful to create a new branch to support this version. Thanks for this great library

**Comment by kostiakoval** [comment]
Yes, thanks

**Comment by davidseek** [comment]
will it come?

**Comment by kostiakoval** [comment]
there is open RP but the test are failing. So there will be Swift 3 support soon

**Comment by davidseek** [comment]
thank you buddy

**Comment by pk1** [comment]
Any news regarding support for Swift 3?

**Comment by kostiakoval** [comment]
the project is update to swift 3. in PR #11 
Closing this issue, since it works now 😍
