### ISSUE TITLE
What is the correct version to be used with Swift 3

### ISSUE THREAD

**Issue by pk1** [kostiakoval/SpeedLog#13]
Hi,

I somehow have no clue what is the correct version to be used with Swift 3. After doing a pod install the version I get is 0.2.2 .But this release seems to be from the last year. It is not containing the fixes\changes that have been done recently in the last few days\week regarding Swift 3.

Any information or tip is highly appreciated!

**Comment by pk1** [comment]
Changing 

pod 'SpeedLog'

to

pod 'SpeedLog', git: 'https://github.com/kostiakoval/SpeedLog.git', branch: 'master'

seems to do the trick.

**Comment by kostiakoval** [comment]
ahh, sorry I have to release new Pod version. Will do it ASAP, thanks

**Comment by kostiakoval** [comment]
<img width="343" alt="screen shot 2016-11-01 at 14 52 10" src="https://cloud.githubusercontent.com/assets/1086260/19891977/d5fa0744-a042-11e6-9d75-0fe8fa189ff8.png">

**Comment by kostiakoval** [comment]
Done!
